name: Build and Deploy

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '3.1.x'

      - name: Build
        run: dotnet build --configuration ${{ env.BUILDCONFIGURATION }}

      - name: Test
        run: dotnet test --configuration ${{ env.BUILDCONFIGURATION }} --no-build

      - name: Publish Functions
        run: dotnet publish DDD.Functions/DDD.Functions.csproj --configuration ${{ env.BUILDCONFIGURATION }} --output ${{ github.workspace }}/${{ github.sha }}

      - name: Azure login
        uses: azure/login@v1
        with:
          client-id: ${{ env.AZURE_CLIENT_ID }}
          tenant-id: ${{ env.AZURE_TENANT_ID }}
          subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}
#        if: github.event_name == 'push' && github.ref == 'refs/heads/master'

      - name: Upload to blob storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload-batch --auth-mode login -d ${{ github.sha }}  --account-name ${{ env.STORAGEACCOUNTNAME }} -s ${{ github.workspace }}/${{ github.sha }}

      - name: Publish Artifacts
        uses: actions/upload-artifact@v4
        with:
          path: ${{ github.workspace }}/${{ github.sha }}
