name: Build and Deploy

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '3.1.x'

      - name: Build
        run: dotnet build --configuration ${{ vars.BUILDCONFIGURATION }}

      - name: Test
        run: dotnet test --configuration ${{ vars.BUILDCONFIGURATION }} --no-build

      - name: Publish Functions
        run: dotnet publish DDD.Functions/DDD.Functions.csproj --configuration ${{ vars.BUILDCONFIGURATION }} --output publish

      - name: Zip Published Files
        run: |
          cd publish
          zip -r ${{ github.sha }}.zip .

      - name: Azure login
        uses: azure/login@v1
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Upload to blob storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload --auth-mode login --overwrite --account-name ${{ vars.STORAGEACCOUNTNAME }} --container-name artifacts --name ${{ github.sha }}.zip --file ${{ github.workspace }}/publish/${{ github.sha }}.zip

      - name: Publish Artifacts
        uses: actions/upload-artifact@v4
        with:
          path: ${{ github.workspace }}/${{ github.sha }}
